name: doctors
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/banner.png
    - assets/img/golden_cardiology.png
    - assets/img/sunrise_clinic.png
    - assets/img/doctors/
    - assets/icons/

